### ISSUE TITLE
pip install transonic fails on MacOS

### ISSUE THREAD

**Issue by jeanlaroche** [fluiddyn/transonic#1]
Here's the error code
```
jlaroche-mbp:Tempo(devel)$ pip install transonic --user
Collecting transonic
  Using cached https://files.pythonhosted.org/packages/70/df/82fd51a2c84589d77d5a92fad025e2a3630da2cf4c2580cab013a4996ae9/transonic-0.1.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j6/7t8sg1vj4q97zhh9z5cdmxbm4rz935/T/pip-install-m90wf5/transonic/setup.py", line 6
        f"In >=2018, you should use a Python supporting f-strings!"
                                                                  ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j6/7t8sg1vj4q97zhh9z5cdmxbm4rz935/T/pip-install-m90wf5/transonic/
```
I'm using python 3.6.5

**Comment by jeanlaroche** [comment]
Similarly, trying to install the wheel does not work. 
```
jlaroche-mbp:Tempo(devel)$ pip install /Users/jlaroche/Downloads/transonic-0.2.3-py3-none-any.whl --user
transonic-0.2.3-py3-none-any.whl is not a supported wheel on this platform.
```
on MacOS, python 3.6.5

**Comment by jeanlaroche** [comment]
I was able to install using the tar.gz installation.

**Comment by jeanlaroche** [comment]
MY BAD! For some reason, I was using pip2 instead of pip3 !!! 
Sorry about the silliness.

**Comment by ashwinvis** [comment]
Thanks for the report. The original error relied on a old version `transonic-0.1.8.tar.gz`.

~~I think the wheel was generated locally since it is a pure-python package. This is strange ....~~ ah OK

**Comment by ashwinvis** [comment]
Classic case of: https://www.xkcd.com/1987/

**Comment by jeanlaroche** [comment]
> Classic case of: https://www.xkcd.com/1987/

ah ah ah! So true!!!
